### ISSUE TITLE
Create Pod "Launch Code" Window

### ISSUE THREAD

**Issue by EUdds** [badgerloop-software/pod-dashboard#10]
When the go button is pressed, we should have a window pop up asking for a "launch code" (password) to add a layer of security before starting the pod.

**Comment by vkottler** [comment]
Why would you need this? If you're trying to require two actions to do something, just use a boolean slider that visually and "mechanically" disables all UI elements that perform actions.

**Comment by EUdds** [comment]
Essentially it boils down to a cool factor we wanted to put in. It's not super important and I figured it would be a good first step for new members to be introduced to the team.

**Comment by EUdds** [comment]
Reassigning this to myself as Michael is busy with work this summer
