### ISSUE TITLE
Creating empty data records on export

### ISSUE THREAD

**Issue by rednazer** [badgerloop-software/pod-dashboard#112]
**Describe the bug**
When recording data sometimes the dashboard does not initialize the daataRecording.js file.

**To Reproduce**
We need to find a way to reproduce this

**Expected behavior**
The exported json's are not initialized

**Comment by pafflitto** [comment]
@rednazer 
### Bug Reproduction
For me, when I first start the pod dashboard and then record and archive data, the data recorded is empty. When I record and archive again without restarting the dashboard then data is recorded.
