### ISSUE TITLE
Make more responsive

### ISSUE THREAD

**Issue by LukeHouge** [badgerloop-software/pod-dashboard#14]
Dashboard is using grid layout, which CAN be very responsive, but is not really setup to be right now. Could change all fonts from using px to being more responsive, and also add css screen size rules for all boxs/divs in the grid layout

**Comment by EUdds** [comment]
The screen we will be using at the competition is most likely going to be 1920x1080 as long as the dashboard is native to the resolution, I don't think this is a high priority.
