### ISSUE TITLE
Charts causing uncaught error

### ISSUE THREAD

**Issue by EUdds** [badgerloop-software/pod-dashboard#38]
**Describe the bug**
When clearing a chart but the dashboard is still running, Plotly is giving an error
(See Screenshot)

**To Reproduce**
1. Launch Dashboard
2. Run Test Pod Server to send data
3. Set either chart to plot any sensor
4. Clear charts
5. See Developer Console

**Expected behavior**
No Error

**Screenshots**
![image](https://user-images.githubusercontent.com/8378883/55199967-0ef84880-518a-11e9-8d63-83a7a834029c.png)

**Additional context**
@alexvesel

**Comment by alexvesel** [comment]
Fixed!
