### ISSUE TITLE
Memory management and Slowdowns

### ISSUE THREAD

**Issue by EUdds** [badgerloop-software/pod-dashboard#88]
**What do you want to change?**
After the dashboard runs for about 15-20 minutes the dashboard starts to slow down. Upon initial looking it seems that this is a memory management issue. Javascript is not known for its garbage collection but we should investigate deeper into why this is happening and what we can do to prevent it.

**Why make that change?**
In some cases we need to run the dash for a considerable amount of time. It is important to make sure we are always running at real-time for an _optimized workflow_ 
**Describe alternatives you've considered**
We are considering dumping data as soon as it is rendered into a file to prevent memory buildup. But more digging is necessary

**Additional context**

**Comment by ezraboley** [comment]
Idea: to mitigate we could just prompt for a refresh periodically (saving connection info)? Like after 15 minutes? Did you ever nail down what was causing this?

**Comment by EUdds** [comment]
@ezraboley Some testing near the beginning of the summer showed that memory usage was acting like an increasing saw tooth, I'll post a pic later. I have been trying to track down what was using increasingly more memory but have had no luck. Tracking this down could fix our problem. 

We could try refreshing every 15 mins but we'd have to test what that does to the connection. It would delete any current recording of data, and we'd need to make sure it doesn't happen during an important time in the state machine (i.e human confirmation of a state change)

**Comment by EUdds** [comment]
![image](https://user-images.githubusercontent.com/8378883/91219629-8b28ef80-e6e0-11ea-9305-00f9fdadfdc1.png)

Fixing the timer solved the memory issues!
