### ISSUE TITLE
Broken drop-down menu

### ISSUE THREAD

**Issue by ezraboley** [badgerloop-software/pod-dashboard#90]
**Describe the bug**
Fix the view select at the top right of the page. It currently disappears when you hover over it unless you click it a very specific way.

**To Reproduce**
1. Hover over the gear icon
2. Observe the drop-down menu
3. Try to use the drop-down menu
4. Struggle

**Expected behavior**
Should stay present and not be difficult to click

**Comment by EUdds** [comment]
@LukeHouge as our resident front-end expert I am assigning you to this issue :)
